apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-webhook-yandex.fullname" . }}
  labels: {{ include "cert-manager-webhook-yandex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector: {{ include "cert-manager-webhook-yandex.selectors" . | nindent 4 }}
